# Generated by Django 5.0.1 on 2024-03-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nameoncard', models.CharField(max_length=250)),
                ('Cardno', models.IntegerField()),
                ('Expirationdate', models.DateField()),
                ('Cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('fullname', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=15)),
                ('password', models.CharField(max_length=8)),
                ('confirmpassword', models.CharField(max_length=8)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('country', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('framesize', models.CharField(default='', max_length=10)),
                ('framecolour', models.CharField(default='', max_length=10)),
                ('framewidth', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(default=None, upload_to='food')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (0, 'UNKNOWN')], default=0)),
            ],
        ),
    ]
