# Generated by Django 5.0 on 2024-04-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
    ]
