# Generated by Django 4.2.4 on 2024-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_name', models.CharField(max_length=250)),
                ('product_price', models.IntegerField()),
                ('product_description', models.TextField(max_length=250)),
                ('product_rate', models.IntegerField()),
                ('product_image', models.ImageField(default=None, upload_to='food')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
