# Generated by Django 4.2.4 on 2024-02-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_rate',
        ),
    ]
