# Generated by Django 5.0 on 2024-02-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0003_remove_product_product_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
