# Generated by Django 5.0.1 on 2024-03-13 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0004_alter_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='glasses.person'),
        ),
        migrations.AddField(
            model_name='product',
            name='modelnumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
