# Generated by Django 5.0.1 on 2024-03-13 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0005_address_person_product_modelnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Person',
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glasses.person'),
        ),
    ]
