# Generated by Django 5.0.1 on 2024-02-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='femaleproduct',
            fields=[
                ('product_name', models.CharField(max_length=250)),
                ('product_price', models.IntegerField()),
                ('product_description', models.TextField(max_length=250)),
                ('product_image', models.ImageField(default=None, upload_to='food')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='maleproduct',
            fields=[
                ('product_name', models.CharField(max_length=250)),
                ('product_price', models.IntegerField()),
                ('product_description', models.TextField(max_length=250)),
                ('product_image', models.ImageField(default=None, upload_to='food')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
