# Generated by Django 5.0.1 on 2024-03-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0006_remove_address_person_address_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Cardno',
            new_name='cardno',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='Cvv',
            new_name='cvv',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='Expirationdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='Nameoncard',
            new_name='nameoncard',
        ),
    ]
