# Generated by Django 5.0.1 on 2024-02-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0006_femaleproduct_maleproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femaleproduct',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maleproduct',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
