# Generated by Django 5.0.1 on 2024-02-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0007_alter_femaleproduct_id_alter_maleproduct_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressline1', models.CharField(max_length=250)),
                ('addressline2', models.CharField(max_length=250)),
                ('pincode', models.IntegerField(max_length=6)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
            ],
        ),
    ]
