# Generated by Django 5.0.1 on 2024-03-14 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0007_rename_cardno_card_cardno_rename_cvv_card_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glasses.person'),
        ),
    ]
