# Generated by Django 5.0.1 on 2024-03-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0008_alter_address_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
