# Generated by Django 5.0 on 2024-02-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0008_addressdetils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetils',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addressdetils',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
