# Generated by Django 5.0.1 on 2024-03-14 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0009_alter_address_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='glasses.address'),
        ),
        migrations.AddField(
            model_name='card',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='glasses.person'),
        ),
    ]
