# Generated by Django 5.0.1 on 2024-03-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0010_card_address_card_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='person',
        ),
    ]
