# Generated by Django 5.0 on 2024-02-28 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0011_addressdetils_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetils',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glasses.person'),
        ),
    ]
