# Generated by Django 5.0.1 on 2024-03-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0011_remove_card_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardno',
            field=models.CharField(max_length=12),
        ),
    ]
