# Generated by Django 5.0 on 2024-02-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0012_alter_addressdetils_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdetils',
            name='country',
        ),
        migrations.RemoveField(
            model_name='addressdetils',
            name='name',
        ),
        migrations.RemoveField(
            model_name='addressdetils',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='addressdetils',
            name='user',
        ),
    ]
